# Let's Build The Model

In [13]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

# Step - 1: Data loading

In [14]:
df = pd.read_csv("D:\\Veena\\Certificate Program in AI and ML\\Certificate-Program-in-AIML-IIT-Patna\\MODULE 2 - CLASSICAL ML\\Dataset\\cardekho_dataset.csv")
df.head(10)

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
5,5,Maruti Wagon R,Maruti,Wagon R,8,35000,Individual,Petrol,Manual,18.90,998,67.10,5,350000
6,6,Hyundai i10,Hyundai,i10,8,40000,Dealer,Petrol,Manual,20.36,1197,78.90,5,315000
7,7,Maruti Wagon R,Maruti,Wagon R,3,17512,Dealer,Petrol,Manual,20.51,998,67.04,5,410000
8,8,Hyundai Venue,Hyundai,Venue,2,20000,Individual,Petrol,Automatic,18.15,998,118.35,5,1050000
9,12,Maruti Swift,Maruti,Swift,4,28321,Dealer,Petrol,Manual,16.60,1197,85.00,5,511000

# Step 2: dropping Unwanted and unnecessary columns, for model

In [15]:
df = df.drop(columns=['Unnamed: 0', 'car_name', 'model'])
print(f"Shape after dropping: {df.shape}")
print(f"Remaining columns: {df.columns.tolist()}")

Shape after dropping: (15411, 11)
Remaining columns: ['brand', 'vehicle_age', 'km_driven', 'seller_type', 'fuel_type', 'transmission_type', 'mileage', 'engine', 'max_power', 'seats', 'selling_price']

In [16]:
df

,brand,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...
15406,Hyundai,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
15407,Maruti,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
15408,Skoda,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
15409,Mahindra,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
15410,Honda,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

# Step 3: Encoding the data

In [17]:
# One-hot encode all categorical columns
df = pd.get_dummies(df, columns=['brand', 'seller_type', 'fuel_type',
                                  'transmission_type'], drop_first=True)

print(f"Shape after encoding: {df.shape}")
print(f"Sample of new columns: {df.columns}")

Shape after encoding: (15411, 45)
Sample of new columns: Index(['vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats',
       'selling_price', 'brand_BMW', 'brand_Bentley', 'brand_Datsun',
       'brand_Ferrari', 'brand_Force', 'brand_Ford', 'brand_Honda',
       'brand_Hyundai', 'brand_ISUZU', 'brand_Isuzu', 'brand_Jaguar',
       'brand_Jeep', 'brand_Kia', 'brand_Land Rover', 'brand_Lexus',
       'brand_MG', 'brand_Mahindra', 'brand_Maruti', 'brand_Maserati',
       'brand_Mercedes-AMG', 'brand_Mercedes-Benz', 'brand_Mini',
       'brand_Nissan', 'brand_Porsche', 'brand_Renault', 'brand_Rolls-Royce',
       'brand_Skoda', 'brand_Tata', 'brand_Toyota', 'brand_Volkswagen',
       'brand_Volvo', 'seller_type_Individual', 'seller_type_Trustmark Dealer',
       'fuel_type_Diesel', 'fuel_type_Electric', 'fuel_type_LPG',
       'fuel_type_Petrol', 'transmission_type_Manual'],
      dtype='str')

In [18]:
df.head(10)

,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price,brand_BMW,brand_Bentley,brand_Datsun,...,brand_Toyota,brand_Volkswagen,brand_Volvo,seller_type_Individual,seller_type_Trustmark Dealer,fuel_type_Diesel,fuel_type_Electric,fuel_type_LPG,fuel_type_Petrol,transmission_type_Manual
0,9,120000,19.70,796,46.30,5,120000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
1,5,20000,18.90,1197,82.00,5,550000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
2,11,60000,17.00,1197,80.00,5,215000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
3,9,37000,20.92,998,67.10,5,226000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
4,6,30000,22.77,1498,98.59,5,570000,False,False,False,...,False,False,False,False,False,True,False,False,False,True
5,8,35000,18.90,998,67.10,5,350000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
6,8,40000,20.36,1197,78.90,5,315000,False,False,False,...,False,False,False,False,False,False,False,False,True,True
7,3,17512,20.51,998,67.04,5,410000,False,False,False,...,False,False,False,False,False,False,False,False,True,True
8,2,20000,18.15,998,118.35,5,1050000,False,False,False,...,False,False,False,True,False,False,False,False,True,False
9,4,28321,16.60,1197,85.00,5,511000,False,False,False,...,False,False,False,False,False,False,False,False,True,True

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 45 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   vehicle_age                   15411 non-null  int64
 1   km_driven                     15411 non-null  int64
 2   mileage                       15411 non-null  float64
 3   engine                        15411 non-null  int64
 4   max_power                     15411 non-null  float64
 5   seats                         15411 non-null  int64
 6   selling_price                 15411 non-null  int64
 7   brand_BMW                     15411 non-null  bool
 8   brand_Bentley                 15411 non-null  bool
 9   brand_Datsun                  15411 non-null  bool
 10  brand_Ferrari                 15411 non-null  bool
 11  brand_Force                   15411 non-null  bool
 12  brand_Ford                    15411 non-null  bool
 13  brand_Honda                   15411 non-null  bool
 14  brand_Hyundai                 15411 non-null  bool
 15  brand_ISUZU                   15411 non-null  bool
 16  brand_Isuzu                   15411 non-null  bool
 17  brand_Jaguar                  15411 non-null  bool
 18  brand_Jeep                    15411 non-null  bool
 19  brand_Kia                     15411 non-null  bool
 20  brand_Land Rover              15411 non-null  bool
 21  brand_Lexus                   15411 non-null  bool
 22  brand_MG                      15411 non-null  bool
 23  brand_Mahindra                15411 non-null  bool
 24  brand_Maruti                  15411 non-null  bool
 25  brand_Maserati                15411 non-null  bool
 26  brand_Mercedes-AMG            15411 non-null  bool
 27  brand_Mercedes-Benz           15411 non-null  bool
 28  brand_Mini                    15411 non-null  bool
 29  brand_Nissan                  15411 non-null  bool
 30  brand_Porsche                 15411 non-null  bool
 31  brand_Renault                 15411 non-null  bool
 32  brand_Rolls-Royce             15411 non-null  bool
 33  brand_Skoda                   15411 non-null  bool
 34  brand_Tata                    15411 non-null  bool
 35  brand_Toyota                  15411 non-null  bool
 36  brand_Volkswagen              15411 non-null  bool
 37  brand_Volvo                   15411 non-null  bool
 38  seller_type_Individual        15411 non-null  bool
 39  seller_type_Trustmark Dealer  15411 non-null  bool
 40  fuel_type_Diesel              15411 non-null  bool
 41  fuel_type_Electric            15411 non-null  bool
 42  fuel_type_LPG                 15411 non-null  bool
 43  fuel_type_Petrol              15411 non-null  bool
 44  transmission_type_Manual      15411 non-null  bool
dtypes: bool(38), float64(2), int64(5)
memory usage: 1.4 MB

# Step 4: Seperating input as x and output as y

In [20]:
x=df.drop(columns=['selling_price'])
y=df['selling_price']

print(f"shape of x: \n{x.shape}")
print(f"\nshape of y: \n{y.shape}")

shape of x:
(15411, 44)

shape of y:
(15411,)

### When to do Scaling - Before split or after Split????

- When we scale the data before the split, we will be hinting the model of how the mean and std deviation of the test data will be. So we should always split the data first and then scale it.
- Another important point is, after splitting we calculate men and std of training data. This will be applied to scale the particular column, of training data. THis is obvious. But the same mean and std will be used to scale the test data as well. We will not calculate the mean and std on test data again for scaling. Because the testing data is completely hidden ir unforeseen by the model. We only have the traing data's statistics. And also we should get the testing data into the traing space be scaling it using training statistics.
- Now when the model sees unforeseen data/future data, agin that data will be scaled using traing statistics. So basically, we are setting our data in the training space of the model. Below is the flow:
New Input -> Scaler (using training mean/std) -> Scaled Input -> Model -> Prediction

# Step 5: Splitting the dataset into train and test.

In [21]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

print(f"shape of x_train: {x_train.shape}, {x_train.shape[0]/len(x)*100 :.0f}% of data")
print(f"shape of x_test: {x_test.shape}, {x_test.shape[0]/len(x)*100 :.0f}% of data")

shape of x_train: (12328, 44), 80% of data
shape of x_test: (3083, 44), 20% of data

# Step 6: Scaling the training set

In [22]:
numericCols=['vehicle_age','km_driven','mileage','engine','max_power','seats']

scalar = StandardScaler()
#fit will find mean and std, transform will apply the standardization formula on each data point.
#This can be done seperately as well, like .fit(), .transform()
x_train[numericCols]=scalar.fit_transform(x_train[numericCols])

print(f"data after scaling: \n{x_train.head(3)}")
print(f"details of x_train after scaling: \n{x_train.describe()}")

data after scaling:
       vehicle_age  km_driven   mileage    engine  max_power     seats  \
11210     0.323969   0.349100 -2.050819  1.756765   2.681685 -0.403824
1347     -1.337798  -1.069394  0.985661 -0.547081  -0.382744 -0.403824
10363    -1.337798  -1.163564 -0.177042  0.893542   3.296910 -0.403824

       brand_BMW  brand_Bentley  brand_Datsun  brand_Ferrari  ...  \
11210      False          False         False          False  ...
1347       False          False         False          False  ...
10363      False          False         False          False  ...

       brand_Toyota  brand_Volkswagen  brand_Volvo  seller_type_Individual  \
11210         False             False         True                   False
1347          False             False        False                    True
10363         False             False        False                   False

       seller_type_Trustmark Dealer  fuel_type_Diesel  fuel_type_Electric  \
11210                         False              True               False
1347                          False             False               False
10363                         False              True               False

       fuel_type_LPG  fuel_type_Petrol  transmission_type_Manual
11210          False             False                     False
1347           False              True                      True
10363          False             False                     False

[3 rows x 44 columns]
details of x_train after scaling:
        vehicle_age     km_driven       mileage        engine     max_power  \
count  1.232800e+04  1.232800e+04  1.232800e+04  1.232800e+04  1.232800e+04
mean   7.262199e-17 -6.916380e-18  1.440912e-17 -1.048984e-16  1.561949e-16
std    1.000041e+00  1.000041e+00  1.000041e+00  1.000041e+00  1.000041e+00
min   -2.002506e+00 -1.291142e+00 -3.780459e+00 -1.325900e+00 -1.449447e+00
25%   -6.730914e-01 -5.985399e-01 -6.574976e-01 -5.509174e-01 -6.166703e-01
50%   -8.384324e-03 -1.276863e-01 -8.882467e-03 -4.530855e-01 -2.774777e-01
75%    6.563227e-01  3.431674e-01  7.118010e-01  1.876176e-01  3.962290e-01
max    7.635747e+00  2.988924e+01  3.315871e+00  9.798164e+00  1.229604e+01

              seats
count  1.232800e+04
mean  -9.625295e-17
std    1.000041e+00
min   -6.589632e+00
25%   -4.038237e-01
50%   -4.038237e-01
75%   -4.038237e-01
max    4.544823e+00

# Step 7: Model Training

In [23]:
model = LinearRegression()
#below line is training the model.
model.fit(x_train,y_train)
# m value for every feature(coefficient)
print(f"No.of coefficients: {model.coef_}")
print(f"Intercept: {model.intercept_}")

No.of coefficients: [-2.27679116e+05 -4.61441160e+04 -1.61215737e+04  7.81262973e+04
  3.35373847e+05  3.61447730e+04  4.05858369e+05  3.66129519e+06
 -7.09797494e+05  3.35712157e+07 -6.84161881e+05 -6.05929376e+05
 -6.34461348e+05 -5.81777427e+05 -5.39248828e+05 -6.72399952e+05
  3.89829810e+05 -3.30328774e+05 -1.88217266e+05  1.37973826e+06
  2.43851701e+06 -3.34953252e+05 -7.57351045e+05 -5.09629233e+05
  3.05324950e+06  1.11758709e-08  2.12192715e+05  5.81734336e+05
 -6.92637218e+05  1.83113118e+06 -6.41815125e+05  1.83478941e+07
 -6.76533456e+05 -8.25722441e+05 -4.17293997e+05 -6.20822305e+05
  1.07324564e+06 -1.20906369e+04 -8.11214717e+04  4.90755661e+04
  2.93031384e+05  2.77714921e+05 -4.11245704e+04 -5.92492214e+04]
Intercept: 1324658.821049799

## Yay!!!! We have created a ML model !!!!

### Now that we have created a mmodel and trained it, how will i know that my model is right? 
- This will be decided on Mean Absolute Error of the model. Meaning, we have y(input data result col). W e will calculate the y`(predicted value by model) by formula y`=m1x1+m2x2+m3x3....+c
- Then we find the absolute difference between the actual val and predicted val. Then we sum and take average. This is known as ***Mean Absolute Error***.

## Creating a baseline model b4 jumping into predictions

In [24]:
import numpy as np

mean_price = y_train.mean()

#Here * is not multiplication it is to repeate the mean_price by len(y_train)
baseline_pred = [mean_price] * len(y_train)
baseline_pred_test = [mean_price] * len(y_test)


print(f"Mean Selling Price (Baseline Prediction): {mean_price:.2f}")
print(f"Baseline MAE over training data: {mean_absolute_error(y_train,baseline_pred):.2f}")
print(f"Baseline MAE over testing data: {mean_absolute_error(y_test,baseline_pred_test):.2f}")

Mean Selling Price (Baseline Prediction): 772120.62
Baseline MAE over training data: 447104.19
Baseline MAE over testing data: 468748.46

# Step 8: Predictions

In [25]:
y_train_pred = model.predict(x_train)
print(f"type of y_train_pred: \n{type(y_train_pred)}")
print(f"y_train_pred: \n{y_train_pred}")

type of y_train_pred:
<class 'numpy.ndarray'>
y_train_pred:
[3412193.03734086  538816.57194792 3107972.2792696  ...  315413.96838231
  792625.57941124 1096655.71792075]

# Step 9: Calculate Mean Absolute Error(MAE)

In [26]:
mae_train = mean_absolute_error(y_train,y_train_pred)
print(f"MAE for training data : {mae_train}")

#The training MAE is far better than my baseline MAE.

MAE for training data : 199219.72900407398

# Step 10: Scale the test data

In [27]:
#We are only doing transform not fit, because we again don't want to calculate mean and std of test data. The scalar obj will have the mean and std of train data.
x_test[numericCols] = scalar.transform(x_test[numericCols])
y_test_pred=model.predict(x_test)
mae_test = mean_absolute_error(y_test,y_test_pred)
print(f"MAE for testing data : {mae_test}")
#The training MAE is far better than my baseline MAE, but worse than training MAE.

MAE for testing data : 212761.44410581276

# Effect of Coefficients on Data

In [28]:
coeff_df = pd.DataFrame({
    "Features":x_train.columns,
    "Coefficients":model.coef_
    }
)
coeff_df['Abs_coeff'] = coeff_df['Coefficients'].abs()
coeff_df = coeff_df.sort_values(['Abs_coeff'],ascending=False)
print(f"coeff_df: \n{coeff_df}")
print(f"Top most 15 impactful features")
print("="*65)
for _, row in coeff_df.head(15).iterrows():
    direction="up" if row["Coefficients"] > 0 else "down"
    bar_len = int(row['Abs_coeff'] / coeff_df['Abs_coeff'].max()*30)
    bar="||" * bar_len
    print(f"{direction} {row['Features']:30s} {bar} ({row['Coefficients']:>+12,.0f})")

print(f"\n Intercept : Rs. {model.intercept_:.0f}")

coeff_df:
                        Features  Coefficients     Abs_coeff
9                  brand_Ferrari  3.357122e+07  3.357122e+07
31             brand_Rolls-Royce  1.834789e+07  1.834789e+07
7                  brand_Bentley  3.661295e+06  3.661295e+06
24                brand_Maserati  3.053250e+06  3.053250e+06
20                   brand_Lexus  2.438517e+06  2.438517e+06
29                 brand_Porsche  1.831131e+06  1.831131e+06
19              brand_Land Rover  1.379738e+06  1.379738e+06
36                   brand_Volvo  1.073246e+06  1.073246e+06
33                    brand_Tata -8.257224e+05  8.257224e+05
22                brand_Mahindra -7.573510e+05  7.573510e+05
8                   brand_Datsun -7.097975e+05  7.097975e+05
28                  brand_Nissan -6.926372e+05  6.926372e+05
10                   brand_Force -6.841619e+05  6.841619e+05
32                   brand_Skoda -6.765335e+05  6.765335e+05
15                   brand_Isuzu -6.724000e+05  6.724000e+05
30                 brand_Renault -6.418151e+05  6.418151e+05
12                   brand_Honda -6.344613e+05  6.344613e+05
35              brand_Volkswagen -6.208223e+05  6.208223e+05
11                    brand_Ford -6.059294e+05  6.059294e+05
13                 brand_Hyundai -5.817774e+05  5.817774e+05
27                    brand_Mini  5.817343e+05  5.817343e+05
14                   brand_ISUZU -5.392488e+05  5.392488e+05
23                  brand_Maruti -5.096292e+05  5.096292e+05
34                  brand_Toyota -4.172940e+05  4.172940e+05
6                      brand_BMW  4.058584e+05  4.058584e+05
16                  brand_Jaguar  3.898298e+05  3.898298e+05
4                      max_power  3.353738e+05  3.353738e+05
21                      brand_MG -3.349533e+05  3.349533e+05
17                    brand_Jeep -3.303288e+05  3.303288e+05
40            fuel_type_Electric  2.930314e+05  2.930314e+05
41                 fuel_type_LPG  2.777149e+05  2.777149e+05
0                    vehicle_age -2.276791e+05  2.276791e+05
26           brand_Mercedes-Benz  2.121927e+05  2.121927e+05
18                     brand_Kia -1.882173e+05  1.882173e+05
38  seller_type_Trustmark Dealer -8.112147e+04  8.112147e+04
3                         engine  7.812630e+04  7.812630e+04
43      transmission_type_Manual -5.924922e+04  5.924922e+04
39              fuel_type_Diesel  4.907557e+04  4.907557e+04
1                      km_driven -4.614412e+04  4.614412e+04
42              fuel_type_Petrol -4.112457e+04  4.112457e+04
5                          seats  3.614477e+04  3.614477e+04
2                        mileage -1.612157e+04  1.612157e+04
37        seller_type_Individual -1.209064e+04  1.209064e+04
25            brand_Mercedes-AMG  1.117587e-08  1.117587e-08
Top most 15 impactful features
=================================================================
up brand_Ferrari                  |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| ( +33,571,216)
up brand_Rolls-Royce              |||||||||||||||||||||||||||||||| ( +18,347,894)
up brand_Bentley                  |||||| (  +3,661,295)
up brand_Maserati                 |||| (  +3,053,250)
up brand_Lexus                    |||| (  +2,438,517)
up brand_Porsche                  || (  +1,831,131)
up brand_Land Rover               || (  +1,379,738)
up brand_Volvo                     (  +1,073,246)
down brand_Tata                      (    -825,722)
down brand_Mahindra                  (    -757,351)
down brand_Datsun                    (    -709,797)
down brand_Nissan                    (    -692,637)
down brand_Force                     (    -684,162)
down brand_Skoda                     (    -676,533)
down brand_Isuzu                     (    -672,400)

 Intercept : Rs. 1324659